name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: lts

      - name: Build Binaries
        run: |
          deno task build:linux
          deno task build:macos
          deno task build:windows

      - name: Compress binaries with UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl
          upx --best --lzma devstream || true
          upx --best --lzma devstream.exe || true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            devstream
            devstream.exe
            devstream.darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: |
            devstream
            devstream.exe
            devstream.darwin
